services:
  app:
    build: .
    ports:
      - 5050:3000
    restart: always
#    develop:
#      watch:
#        - action: sync+restart
#          path: ./app
#          target: /app
#          ignore:
#            - views
#        - action: sync
#          path: ./app/views
#          target: /app/views

